from ..typecheck import *

if TYPE_CHECKING:
	from . html import element


class SyntaxHighlightedText:
	def __init__(self, text: str, language: str) -> None:
		self.html = None #type: Optional[str]
		self.text = text
		self.language = language


class Layout:
	def dirty(self) -> None:
		...
	def remove_component_children(self, item: 'element') -> None:
		...
	def remove_component(self, item: 'element') -> None:
		...
	def add_component_children(self, item: 'element') -> None:
		...
	def add_component(self, item: 'element') -> None:
		...
	def render_component_tree(self, item: 'element') -> None:
		...
	def render_component(self, item: 'element') -> None:
		...
	def run_syntax_highlight(self) -> None:
		...
	def render(self) -> bool:
		...
	def syntax_highlight(self, text: str, language: str) -> SyntaxHighlightedText:
		...
	def dispose(self) -> None:
		...
	def em_width(self) -> float:
		...
	def width(self) -> float:
		...
	def height(self) -> float:
		...
	def luminocity(self) -> float:
		...
	def on_navigate_main(self, path: str):
		...
	def on_navigate(self, path: str) -> None:
		...
	def register_on_click_handler(self, callback: 'Callable') -> str:
		...
