TYPE_CHECKING = False

class Any:
	...
class Protocol:
	...
class Generic:
	def __class_getitem__(self, params):
		return self
	...
class Generator(Generic):
	...
class Callable(Generic):
	...
class List(Generic):
	...
class Optional(Generic):
	...
class Tuple(Generic):
	...
class Union(Generic):
	...
class Dict(Generic):
	...
class Set(Generic):
	...
class Sequence(Generic):
	...
class Iterable(Generic):
	...
class NamedTuple(Generic):
	...
class TypeVar:
	def __init__(self, name: str) -> None:
		...
def overload(func):
	def overload(*args, **kwds):
		raise NotImplementedError
	return overload
